apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-config-deployment
  labels:
    app: backend-config-deployment
spec:
  selector:
    matchLabels:
      app: backend-config-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-config-deployment
    spec:
      containers:
        - name: topeducation-config-postgres
          image: ncarcamo/topeducation-config-postgres:latest
          ports:
            - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: configService
  labels:
    app: configService
spec:
  selector:
    app: backend-config-deployment
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
  type: LoadBalancer