apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-gateway-deployment
  labels:
    app: backend-gateway-deployment
spec:
  selector:
    matchLabels:
      app: backend-gateway-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-gateway-deployment
    spec:
      containers:
        - name: topeducation-gateway-postgres
          image: ncarcamo/topeducation-gateway-postgres:latest
          ports:
            - containerPort: 9001
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:9001
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  labels:
    app: gateway-service
spec:
  selector:
    app: backend-gateway-deployment
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
  type: LoadBalancer