apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cuotas-deployment
  labels:
    app: backend-cuotas-deployment
spec:
  selector:
    matchLabels:
      app: backend-cuotas-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: backend-cuotas-deployment
    spec:
      containers:
        - name: topeducation-cuotas-postgres
          image: ncarcamo/topeducation-cuotas-postgres:latest
          ports:
            - containerPort: 9001
          env:
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service:9001
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eureka-service:8761
            - name: eureka.instance.preferIpAddress
              value: "true"
            - name: POSTGRES_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_HOST
            - name: POSTGRES_DB_CUOTAS
              valueFrom:
                configMapKeyRef:
                  name: postgres-config-map
                  key: POSTGRES_DB_CUOTAS
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: topeducuotas
  labels:
    app: topeducuotas
spec:
  selector:
    app: backend-cuotas-deployment
  ports:
    - protocol: TCP
      port: 9003
      targetPort: 9003
  type: LoadBalancer  