server:
  port: 9001
spring:
  application:
    name: backend-config-service
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/ncarcamoe/mingeso_micro
          search-paths: "config-data-mingeso"